export const MISSION_ROUTE = '/missiya'
export const NOT_FOUND = '*'
export const HISTORY_ROUTE = '/history'
export const STRUCTURE_ROUTE = '/structure'
export const FOUNDERS_ROUTE = '/founders'
export const DEVELOPMENT_ROUTE = '/devop'
export const PRESIDENT_ROUTE = '/president'
export const TEST_ROUTE = '/test'